feat(front): basic component
tomyo002/souin-desktop pull request #2
Opened 2024-04-16 14:34 UTC by tomyo002

creation of basic components

2024-04-17 09:37 UTC, tomyo002 commented
les problèmes d'eslint sont régler dans le #3

2024-04-17 20:06 UTC, darkweak commented
> les problèmes d'eslint sont régler dans le #3

Please speak English.

2024-04-17 20:12 UTC, darkweak requested changes

2024-04-17 20:12 UTC, darkweak commented on frontend/src/components/atomic/Button.tsx
> +  classname?: string;
You must add a global ClassName prop and use it everywhere you need it.  
e.g.
```
// anywhere/global.ts
type ClassName = { className?: string };
```

```
// your_components/component.ts
type ButtonProps = ClassName & { ... your props here ... };

2024-04-17 20:12 UTC, darkweak commented on frontend/src/components/atomic/Button.tsx
> +  onclick?: (params?: unknown) => void;
Respect the component API, `onClick`.

2024-04-17 20:12 UTC, darkweak commented on frontend/src/components/atomic/Button.tsx
> +  children: ReactNode;
You don't have to declare `children` here.

2024-04-17 20:12 UTC, darkweak commented on frontend/src/components/atomic/Button.tsx
> +type PropsButton = {
Your props type must be like `YourComponentNameProps`.

2024-04-17 20:12 UTC, darkweak commented on frontend/src/components/atomic/H2.tsx
> +  classname?: string;
Same.

2024-04-17 20:12 UTC, darkweak commented on frontend/src/components/atomic/H2.tsx
> +type PropsH2 = {
Same.

2024-04-17 20:12 UTC, darkweak commented on frontend/src/components/atomic/Icon.tsx
> +): ComponentType<React.SVGProps<SVGSVGElement>> | undefined {
Prefer return a default `Icon` instead of undefined.

2024-04-17 20:12 UTC, darkweak commented on frontend/src/components/atomic/index.ts
> +export * from './Image';
Add NL.

2024-04-17 20:12 UTC, darkweak commented on frontend/src/components/molecule/Card.tsx
> +);
Add NL.

2024-04-17 20:12 UTC, darkweak commented on frontend/src/components/molecule/index.ts
> +export * from "./Card";
Add NL.

2024-04-17 20:12 UTC, darkweak commented on frontend/src/components/atomic/Icon.tsx
> +  classname?: string;
Same.

2024-04-17 20:12 UTC, darkweak commented on frontend/src/components/atomic/Icon.tsx
> +type PropsIcon = {
Same.

2024-04-17 20:12 UTC, darkweak commented on frontend/src/components/atomic/H1.tsx
> +type PropsH1 = {
Same.

2024-04-17 20:12 UTC, darkweak commented on frontend/src/components/atomic/H1.tsx
> +  classname?: string;
Same.

2024-04-17 20:12 UTC, darkweak commented on frontend/src/components/atomic/Image.tsx
> +type PropsImage = {
Same.

2024-04-17 20:12 UTC, darkweak commented on frontend/src/components/atomic/Image.tsx
> +  classname?: string;
Same.

2024-04-17 20:12 UTC, darkweak commented on frontend/src/components/atomic/Image.tsx
> +export const Image: React.FC<PropsImage> = ({ classname, ...rest }) => (
You don't have to extract the className after renaming the property.

2024-04-18 08:19 UTC, darkweak approved these changes

2024-04-18 09:22 UTC, merged