Feat(front): switch storage
tomyo002/souin-desktop pull request #20
Opened 2024-05-24 08:05 UTC by tomyo002

2024-05-24 08:38 UTC, tomyo002 commented
Avant
![Capture d’écran du 2024-05-24 10-37-45](https://github.com/tomyo002/souin-desktop/assets/132358409/98792a12-b448-417e-bcb3-49b83643df7a)
Apres
![Capture d’écran du 2024-05-24 10-38-10](https://github.com/tomyo002/souin-desktop/assets/132358409/c6f352c1-1f37-4583-a1e5-efa5b6c26d07)

2024-05-28 13:08 UTC, darkweak requested changes

2024-05-28 13:08 UTC, darkweak commented on frontend/src/context/StorageProvider.tsx
> +  const [storage, setStorage] = useState<AllowedStorage>('localStorage');
```suggestion
  const [storage, setStorage] = useState<IStorage>(new InstanceData());
  const updateStorage(name: string) {
    setStorage(new InstanceData(name));
  }
```

2024-05-28 13:08 UTC, darkweak commented on frontend/src/service/class/Storage.tsx
> +    }
```suggestion
    let current: IStorage;
    switch (storage) {
      case 'sqliteStorage':
        current = this.sqliteStorage;
        break;
      default:
        current = this.localStorage;
    }
    
    return current.get();
```

2024-05-28 13:08 UTC, darkweak commented on frontend/src/context/StorageProvider.tsx
> +    useState<AllowedStorage>('localStorage');
Useless.

2024-05-28 13:08 UTC, darkweak commented on frontend/src/components/page/HomePage.tsx
> +const allowStorage = (value: string): value is AllowedStorage => {
That's an `is`-er function.

2024-05-28 13:08 UTC, darkweak commented on frontend/src/context/StorageProvider.tsx
> +  return storage;
Missing new line.

2024-05-28 13:08 UTC, darkweak commented on frontend/src/context/StorageProvider.tsx
> +  return { currentType, setStorage };
Missing new line.

2024-05-28 13:08 UTC, darkweak commented on frontend/src/service/class/Storage.tsx
> +  async get() {
Missing new line.

2024-05-28 13:08 UTC, darkweak commented on frontend/src/service/class/Storage.tsx
> +  async set(instances: readonly InstanceType[]) {
Missing new line.

2024-05-28 13:08 UTC, darkweak commented on frontend/src/service/class/Storage.tsx
> +  async set(instances: readonly InstanceType[]) {
Why not using the ReadonlyArray type?

2024-05-28 13:08 UTC, darkweak commented on frontend/src/service/class/Storage.tsx
> +  async delete() {
Missing new line.

2024-05-29 12:21 UTC, darkweak requested changes

2024-05-29 12:21 UTC, darkweak commented on frontend/src/components/page/HomePage.tsx
> +              }}
Don't need extra curly brackets.

2024-05-29 12:21 UTC, darkweak commented on frontend/src/context/StorageProvider.tsx
> +export type AllowedStorage = 'localStorage' | 'sqliteStorage';
Store these as const to avoid typos.

2024-05-29 13:31 UTC, darkweak requested changes

2024-05-29 13:31 UTC, darkweak commented on frontend/src/context/StorageProvider.tsx
> +  storage: new InstanceData('localStorage'),
Use the constant.

2024-05-29 13:31 UTC, darkweak commented on frontend/src/context/StorageProvider.tsx
> +    new InstanceData('localStorage'),
Use the constant.

2024-05-29 13:31 UTC, darkweak commented on frontend/src/service/instance.tsx
>  }
IMHO this can be removed.

2024-05-29 13:31 UTC, darkweak requested changes

2024-05-29 13:31 UTC, darkweak commented on frontend/src/service/instance.tsx
>  }
IMHO this can be removed

2024-05-30 07:26 UTC, darkweak requested changes

2024-05-30 07:26 UTC, darkweak commented on frontend/src/context/StorageProvider.tsx
> +};
Because you're returning all props, you can just return your useContext.

2024-05-30 14:55 UTC, darkweak approved these changes

2024-05-31 07:34 UTC, merged