Feat(front) better UX about instance
tomyo002/souin-desktop pull request #31
Opened 2024-06-06 08:21 UTC by tomyo002

2024-06-06 11:23 UTC, darkweak commented
Put a screenshot about the result.

2024-06-06 12:06 UTC, tomyo002 commented
![Capture d’écran du 2024-06-06 14-06-32](https://github.com/tomyo002/souin-desktop/assets/132358409/1c33a3c1-35b4-4fc7-9d66-bb9ddef14812)

2024-06-06 12:45 UTC, darkweak requested changes

2024-06-06 12:45 UTC, darkweak commented on frontend/src/components/atomic/Icon.tsx
> +  return <Icon className={!className ? 'h-6 w-6' : className} />;
```suggestion
  return <Icon className={className || 'h-6 w-6'} />;
```

2024-06-06 12:45 UTC, darkweak commented on frontend/src/components/atomic/Icon.tsx
> +  return <Icon className={!className ? 'h-6 w-6' : className} />;
`className ?? 'h-6 w-6'`

2024-06-06 13:48 UTC, tomyo002 commented
![Capture d’écran du 2024-06-06 15-48-39](https://github.com/tomyo002/souin-desktop/assets/132358409/9a89eaba-a127-4305-88d3-37e06981f407)

2024-06-07 13:03 UTC, darkweak commented
There are still differences between the expectation and your proposition

2024-06-11 12:47 UTC, darkweak commented
@tomyo002 what about this PR?

2024-06-11 14:23 UTC, tomyo002 commented
![Capture d’écran du 2024-06-11 16-22-42](https://github.com/tomyo002/souin-desktop/assets/132358409/73a9216f-826e-418b-b278-05eefcaf2e1b)

2024-06-11 15:11 UTC, darkweak commented
@tomyo002 Still not the same as expected!

2024-06-12 14:24 UTC, tomyo002 commented
![Uploading Capture d’écran du 2024-06-12 16-23-40.png…]()

2024-06-12 14:25 UTC, tomyo002 commented
![Capture d’écran du 2024-06-12 16-23-40](https://github.com/tomyo002/souin-desktop/assets/132358409/76bf0df8-15f9-43d0-b323-96861858cce2)

2024-06-13 17:44 UTC, darkweak requested changes

2024-06-13 17:44 UTC, darkweak commented on frontend/src/components/layout/Menu.tsx
> +                )}
You don't need javascript to display that.

2024-06-13 17:44 UTC, darkweak commented on frontend/src/components/layout/Menu.tsx
> +  };
Basically, using `mouseEnter` and `mouseLeave` is a bad idea.

2024-06-14 09:15 UTC, darkweak approved these changes

2024-06-14 09:16 UTC, merged