Feat(front): realization page with css
tomyo002/souin-desktop pull request #5
Opened 2024-04-18 13:00 UTC by tomyo002

2024-04-18 20:14 UTC, darkweak requested changes
When I asked about screenshots, it was in the PR description, not in the code/repository.

2024-04-18 20:14 UTC, darkweak commented on frontend/src/style.css
> +}
Missing NL.

2024-04-19 13:01 UTC, tomyo002 commented
![Capture d’écran du 2024-04-19 14-23-40](https://github.com/tomyo002/souin-desktop/assets/132358409/d6fc3f2a-2017-476a-a7a2-96d1cbadb997)
![Capture d’écran du 2024-04-19 14-24-03](https://github.com/tomyo002/souin-desktop/assets/132358409/03b1845f-a369-42a9-95c4-07cd9a50bf3c)

2024-04-19 13:22 UTC, darkweak requested changes
Take the time to apply all previous comments in your previous PRs

2024-04-19 13:22 UTC, darkweak commented on frontend/src/components/layout/Footer.tsx
> +      </svg>
Useless SVG right?

2024-04-19 13:22 UTC, darkweak commented on frontend/src/components/layout/Navbar.tsx
> +type PropsNavbar = {
Naming.

2024-04-19 13:22 UTC, darkweak commented on frontend/src/components/molecule/Connected.tsx
> +type PropsConnected = {
Naming.

2024-04-19 13:22 UTC, darkweak commented on frontend/src/components/molecule/DisplayQuantile.tsx
> +          const path = lines[index].metrics[0];
You're accessing to one `metric` so why not naming your var `metric`?

2024-04-19 13:22 UTC, darkweak commented on frontend/src/components/molecule/DisplayQuantile.tsx
> +  const ResetClick = () => {
Do you need this constant?

2024-04-19 13:22 UTC, darkweak commented on frontend/src/components/page/DisplayPage.tsx
> +      <div className="flex flex-col ">
```suggestion
      <div className="flex flex-col">
```
By the way, `flex flex-col` with only one item?

2024-04-19 13:22 UTC, darkweak commented on frontend/src/components/page/DisplayPage.tsx
> +type PropsDisplayPage = {
Naming.

2024-04-19 13:22 UTC, darkweak commented on frontend/tailwind.config.js
> +    themes: ['light', 'coffee'],
`coffee`? Really?

2024-04-19 13:22 UTC, darkweak commented on main.go
> +		Height: 853,
Arbitrary height?

2024-04-21 17:20 UTC, darkweak commented
Here is what it should look like:
![image](https://github.com/tomyo002/souin-desktop/assets/25440709/7534a276-6fb9-45e8-b3ff-0661ca111066)

I removed the theme switch and made a multiline graph so it can be reused easier.

2024-04-26 14:35 UTC, darkweak requested changes

2024-04-26 14:35 UTC, darkweak commented on frontend/src/components/molecule/MultiLineData.tsx
> +                  : data['data'];
```diff
            return current.map(({ data }) => {
              const currentData =
                data.length >= max
                  ? data.slice(1)
                  : data;
```

2024-04-26 14:35 UTC, darkweak commented on frontend/src/service/fetcher.tsx
> +      return 'ok';
Plaintext `'ok'`? Why?

2024-04-26 14:35 UTC, darkweak commented on frontend/src/components/molecule/HealthCheck.tsx
> +        if (response === null) {
Simplify this check.

2024-04-26 14:35 UTC, darkweak commented on frontend/src/components/molecule/MultiLineData.tsx
> +        } else {
duplicated code.

2024-04-26 14:35 UTC, darkweak commented on frontend/src/components/molecule/MultiLineData.tsx
> +      return {
`return` not needed.

2024-04-26 14:35 UTC, darkweak commented on frontend/src/components/molecule/MultiLineData.tsx
> +                borderColor: data.borderColor,
Simplify.

2024-04-26 14:35 UTC, darkweak commented on frontend/src/components/molecule/MultiLineData.tsx
> +        const currentLabel = current.length >= max ? current.slice(1) : current;
simplify.

2024-04-26 14:35 UTC, darkweak commented on frontend/src/components/molecule/MultiLineData.tsx
> +              const currentData =
Useless assignment.

2024-04-26 14:35 UTC, darkweak commented on frontend/src/components/layout/Footer.tsx
> +import React from 'react';
Rework.

2024-04-26 14:35 UTC, darkweak commented on frontend/src/components/molecule/Line.tsx
> +  labels: Array<string>;
`ReadonlyArray`

2024-04-26 15:58 UTC, darkweak requested changes

2024-04-26 15:58 UTC, darkweak commented on frontend/src/components/molecule/MultiLineData.tsx
> +            return {
`return` to needed.

2024-04-26 15:58 UTC, darkweak commented on frontend/src/components/molecule/MultiLineData.tsx
> +          return currents.map(({ data, label, ...rest }) => {
`return` to needed.

2024-04-26 15:58 UTC, darkweak commented on frontend/src/components/molecule/MultiLineData.tsx
> +              label: label,
To simplify.

2024-04-26 15:58 UTC, darkweak commented on frontend/src/service/fetcher.tsx
> +  });
return a boolean.

2024-04-26 15:58 UTC, darkweak commented on frontend/src/components/layout/Footer.tsx
> +  <footer className="footer-center p-4 bg-neutral text-neutral-content">
`footer` className is missing.

2024-04-29 09:07 UTC, darkweak approved these changes

2024-04-29 09:07 UTC, darkweak commented on frontend/src/components/layout/Navbar.tsx
> +      </a>
Use span instead.

2024-04-29 09:07 UTC, darkweak commented on frontend/src/components/layout/Navbar.tsx
> +    <div className="flex-none">
Not needed.

2024-04-29 09:07 UTC, darkweak commented on frontend/src/components/molecule/HealthCheck.tsx
> +    }, 1000);
Remove the interval, check only once.

2024-04-29 09:16 UTC, merged